name: Terraform CI (Dry Run)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Validation Workflow
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: multi_env/envs/dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init (No backend)
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      # Optional: Plan just to test syntax (commented to avoid real usage)
      # - name: Terraform Plan (Dry run)
      #   run: terraform plan -var-file=terraform.tfvars
